[package]
name = "rust-xml"
version = "0.1.0"
authors = ["fox0"]
edition = "2018"
publish = false

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde-xml-rs = "0.4"
validator = { version = "0.12", features = ["derive"] }
