[package]
name = "rust-xml"
version = "0.1.0"
authors = ["fox0"]
edition = "2018"
publish = false

[dependencies]
#serde = { version = "1.0", features = ["derive"] }
serde = "1.0"
serde_derive = "1.0"
serde-xml-rs = "0.4"
