//! DO NOT EDIT! Generated by gen_models.py

// from schemas/запрос-авторизация.xsd

/// Блок авторизации
#[derive(Debug, Serialize)]
pub struct AuthData {
    /// Номер заявления ОУ
    #[serde(rename = "Login", default)]
    // max_length = 50
    pub login: String,
    /// Пароль
    #[serde(rename = "Pass", default)]
    // max_length = 50
    pub pass: String,
    /// Идентификатор ВУЗа
    #[serde(rename = "InstitutionID", default)]
    pub institution_id: Option<u64>,
}

#[derive(Debug, Serialize, Deserialize, PartialEq)]
pub struct Item {
    name: String,
    source: String,
}

#[derive(Debug, Deserialize)]
pub struct Project {
    pub name: String,
    #[serde(rename = "Item", default)]
    pub items: Vec<Item>,
}
