//! DO NOT EDIT! Generated by gen_models.py
#[allow(unused_imports)]
use serde::{Serialize, Deserialize};
#[allow(unused_imports)]
use validator::Validate;

// schemas/запрос-авторизация.xsd

/// Блок авторизации
#[derive(Debug, Validate, Serialize)]
#[serde(rename_all = "PascalCase")]
pub struct AuthData {
    /// Номер заявления ОУ
    #[validate(length(max = 50))]
    pub login: String,
    /// Пароль
    #[validate(length(max = 50))]
    pub pass: String,
    /// Идентификатор ВУЗа
    #[serde(skip_serializing_if = "Option::is_none")]
    pub institution_id: Option<u64>,
}

#[derive(Debug, Serialize, Deserialize, PartialEq)]
pub struct Item {
    name: String,
    source: String,
}

#[derive(Debug, Deserialize)]
pub struct Project {
    pub name: String,
    #[serde(rename = "Item", default)]
    pub items: Vec<Item>,
}
